-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 12:06:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventdb` DEFAULT CHARACTER SET utf8 ;
USE `eventdb` ;

-- -----------------------------------------------------
-- Table `eventdb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventdb`.`Event` ;

CREATE TABLE IF NOT EXISTS `eventdb`.`Event` (
  `EventId` CHAR(36) NOT NULL,
  `EventName` VARCHAR(45) NOT NULL,
  `EventCategory` VARCHAR(30) NOT NULL,
  `EventDate` DATE NOT NULL,
  `EventLocation` VARCHAR(40) NOT NULL,
  `EventCapacity` CHAR(10) NOT NULL,
  PRIMARY KEY (`EventId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventdb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventdb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `eventdb`.`Customer` (
  `CustomerId` CHAR(36) NOT NULL,
  `CustomerName` VARCHAR(50) NOT NULL,
  `CustomerPhoneNo` CHAR(12) NOT NULL,
  `CustomerEmail` VARCHAR(45) NOT NULL,
  `EventId` CHAR(36) NOT NULL,
  PRIMARY KEY (`CustomerId`),
  INDEX `fk_Customer_Event_idx` (`EventId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Event`
    FOREIGN KEY (`EventId`)
    REFERENCES `eventdb`.`Event` (`EventId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
